### ISSUE TITLE
Show hidden files

### ISSUE THREAD

**Issue by demonkillerr** [tcet-opensource/tcet-linux-settings#1]
Show hidden files doesn't work

**Comment by Akash6222** [comment]
In my case it works

**Comment by Akash6222** [comment]
Ohh got it after right click inside the thunar file manager , the show hidden file button doesn't work.

**Comment by Akash6222** [comment]
The root cause is that xdotool package is installed.

**Comment by Akash6222** [comment]
Closing this issue and creating new issue on tcet-linux repo
